### ISSUE TITLE
Enable multilanguage articles with translations in `<sub-article>`s

### ISSUE THREAD

**Issue by lpanebr** [elifesciences/lens#227]
# Description

### What is the Problem?

Translations in `<sub-article>` are not processed.

### What is the benefit of solving the problem?

Many journals that use the Scielo and PMC JATS style[1,2], and tag multilingual articles with each translation in a `<sub-article>`[3] would be very happy and LOTs of content would be accessible to a larger audience.

### How will we know when the problem has been solved?

The article will be presented with `<sub-article>` contents properly rendered. PMC and Scielo solve this differently:
 - **PMC**: Single HTML page and single PDF.
 - **Scielo**: Individual HTML and PDFs.

**Examples:**
 - [Sample PMC article with translation](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC8153203/)
 - [Sample Scielo article with translation](https://www.scielo.br/j/jvb/a/hGjBTtqBFcDrnZXXJ8hyWwf/?lang=en)

### How could we measure the impact or benefit of the solution?

Adding quick access links to the translations and other content in `<sub-article>`s and tracking it's usage in any analytics tools.

# Documents and Resources

 - [Sample PMC article with translation](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC8153203/)
 - [Sample Scielo article with translation](https://www.scielo.br/j/jvb/a/hGjBTtqBFcDrnZXXJ8hyWwf/?lang=en)

[1] https://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/dobs.html#dob-multi-lang
[2] https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-sub-article.html?highlight=sub-article
[3] https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/sub-article.html

# Tasks

List of any initial tasks, if applicable, that you think might need to be done to progress this issue. e.g...
- [ ] Investigate if there are any open-source search implementations out there. 
- [ ] Setup meeting to identify stakeholders.
- [ ] Approving the task.
- [ ] Collecting lots of XML samples. (just ask me)
- [ ] Handling it to the developers for their initial technical evaluation and compilation of thoughts and list of concerns.
- [ ] Evaluation and answering each concern. (just ask me)
- [ ] Getting it done.
- [ ] 🍾

# Definition of Done

- [ ] Solution properly handles multiple `<sub-article>`s for one article with many translations.
- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.
- [ ] Solution has been announced to the community.

**Comment by gnott** [comment]
Thanks for adding the description here @lpanebr!

**Comment by lpanebr** [comment]
You're welcome @gnott ! Is this project still active and maintained by elife??

**Comment by gnott** [comment]
Hi @lpanebr, the short answer is eLife is still involved (via myself), and primarily only applying security updates rather than adding new features.

**Comment by lpanebr** [comment]
OK, thank you @gnott for your answer and work. This is such a great project!
It seems it's still in use by eLife so would by lying if I said I'm not curious in the long answer... 😉

The reason for my curiosity is both using it directly and also as the driver for the OJS lensGalley plugin (https://github.com/asmecher/lensGalley).


Thanks again!!

**Comment by gnott** [comment]
Very cool! I don't have a full picture of every project which used Lens and uses it now, and I worry about breaking things by accident, unless they are running from their own forks.

A slightly longer answer is due to limited developer time available, and other projects have a higher priority, even the Lens issues described for eLife articles (in a separate internal issues board) are waiting until there's more direction from the planning team.

Next up is to build better automated testing, so it doesn't require manual testing after to a code change.

**Comment by lpanebr** [comment]
Yeah.... not enough dev time is tough when we have many projects. I suffer
from that too.
Thank you so much for your expanded answer!!
I'll keep watching.
